#!/usr/bin/env bash
#
# One-shot deploy: builds and starts the API, web app, admin console and
# Postgres. Safe to re-run — it rebuilds changed images and restarts in place.
#
#   ./deploy.sh              build + start everything
#   ./deploy.sh logs         follow logs
#   ./deploy.sh stop         stop containers (data is kept)
#   ./deploy.sh restart      restart without rebuilding
#   ./deploy.sh seed         run the database seed
#   ./deploy.sh destroy      stop and DELETE the database volume
#
set -euo pipefail

cd "$(dirname "$0")"

RED=$'\033[0;31m'; GREEN=$'\033[0;32m'; YELLOW=$'\033[0;33m'; BLUE=$'\033[0;34m'; NC=$'\033[0m'
info()  { echo "${BLUE}==>${NC} $*"; }
ok()    { echo "${GREEN}  ok${NC} $*"; }
warn()  { echo "${YELLOW}  !!${NC} $*"; }
die()   { echo "${RED}error:${NC} $*" >&2; exit 1; }

SERVER_PORT=4000
WEB_PORT=3000
ADMIN_PORT=3001

# The public address of this deployment (DigitalOcean droplet). The web and
# admin bundles are compiled to call the API here, so it must be the address a
# BROWSER can reach — not `localhost`, unless you are deploying on your laptop.
# Override per-machine by setting PUBLIC_API_URL in .env.
DEPLOY_HOST="${DEPLOY_HOST:-178.128.144.198}"

# --- docker compose detection ----------------------------------------------
command -v docker >/dev/null 2>&1 || die "docker is not installed — see https://docs.docker.com/get-docker/"
docker info >/dev/null 2>&1 || die "the docker daemon is not running — start Docker and retry"

if docker compose version >/dev/null 2>&1; then
  COMPOSE=(docker compose)
elif command -v docker-compose >/dev/null 2>&1; then
  COMPOSE=(docker-compose)
else
  die "docker compose is not available"
fi

# --- environment ------------------------------------------------------------
# Compose reads ./.env automatically; this block just makes sure it exists and
# carries a real AUTH_SECRET before we hand over to compose.
ensure_env() {
  if [ ! -f .env ]; then
    info "No .env found — creating one"
    secret="$(openssl rand -hex 32 2>/dev/null || head -c 32 /dev/urandom | od -An -tx1 | tr -d ' \n')"
    cat > .env <<EOF
# Generated by deploy.sh. Edit before deploying anywhere public.
POSTGRES_USER=postgres
POSTGRES_PASSWORD=$(openssl rand -hex 16 2>/dev/null || echo "password")
POSTGRES_DB=afridata
# Signs admin session tokens. Changing it signs everyone out.
AUTH_SECRET=$secret

# The API URL the BROWSER will call. Baked into the web/admin bundles at build
# time, so change it here and re-run ./deploy.sh to take effect.
# Use http://localhost:$SERVER_PORT only when running on your own machine.
PUBLIC_API_URL=http://$DEPLOY_HOST:$SERVER_PORT

# Set true to run the database seed on each server start.
SEED_ON_START=false
EOF
    ok "wrote .env with a generated AUTH_SECRET"
    warn "review .env — PUBLIC_API_URL must be reachable from the browser"
  fi

  # shellcheck disable=SC1091
  set -a; . ./.env; set +a

  [ -n "${AUTH_SECRET:-}" ] || die "AUTH_SECRET is empty in .env"
  case "${AUTH_SECRET:-}" in
    change-me*) die "AUTH_SECRET in .env is still the placeholder — set a real value" ;;
  esac
}

check_ports() {
  for p in "$SERVER_PORT" "$WEB_PORT" "$ADMIN_PORT"; do
    # Only warn: the port may well be held by a previous run of this stack,
    # which compose is about to replace.
    if lsof -iTCP:"$p" -sTCP:LISTEN >/dev/null 2>&1; then
      warn "port $p is already in use — compose will fail if it is not this stack"
    fi
  done
}

deploy() {
  ensure_env
  check_ports

  info "Building images (this takes a few minutes the first time)"
  "${COMPOSE[@]}" build

  info "Starting containers"
  "${COMPOSE[@]}" up -d --remove-orphans

  info "Waiting for the API to become healthy"
  for i in $(seq 1 60); do
    if curl -fsS "http://localhost:$SERVER_PORT/health" >/dev/null 2>&1; then
      ok "API is up"
      break
    fi
    if [ "$i" = 60 ]; then
      warn "API did not answer /health in time — recent logs:"
      "${COMPOSE[@]}" logs --tail=40 server
      die "deploy failed"
    fi
    sleep 2
  done

  # Show the address the bundles were actually built to call.
  host="$(printf '%s' "${PUBLIC_API_URL:-http://localhost:$SERVER_PORT}" | sed -E 's#^https?://##; s#:[0-9]+$##')"
  echo
  ok "Deployed"
  echo "   web    http://$host:$WEB_PORT"
  echo "   admin  http://$host:$ADMIN_PORT"
  echo "   api    http://$host:$SERVER_PORT"
  echo
  echo "   logs   ./deploy.sh logs"
  echo "   stop   ./deploy.sh stop"
}

case "${1:-deploy}" in
  deploy|"")  deploy ;;
  logs)       "${COMPOSE[@]}" logs -f --tail=100 ;;
  stop|down)  info "Stopping"; "${COMPOSE[@]}" down; ok "stopped (database volume kept)" ;;
  restart)    info "Restarting"; "${COMPOSE[@]}" restart; ok "restarted" ;;
  ps|status)  "${COMPOSE[@]}" ps ;;
  seed)       ensure_env; info "Seeding"; "${COMPOSE[@]}" exec server node dist/prisma/seed.js; ok "seeded" ;;
  destroy)
    read -r -p "This deletes the database volume. Type 'yes' to confirm: " reply
    [ "$reply" = "yes" ] || die "aborted"
    "${COMPOSE[@]}" down -v
    ok "stack and database volume removed"
    ;;
  *) die "unknown command '$1' — use: deploy | logs | stop | restart | ps | seed | destroy" ;;
esac
